old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     true

    producers:
        identity_producer:
            connection:       default
            exchange_options: { name: 'identityCreatedExchange', type: fanout }

    consumers:
        identity_consumer:
            connection:       default
            exchange_options: { name: 'identityCreatedExchange', type: fanout }
            queue_options:    { name: 'identityCreatedQueue.account' }
            callback:         'App\Account\Ui\Amqp\IdentityConsumer'
