version: '3'

services:
###> doctrine/doctrine-bundle ###
  exchange-db:
    image: postgres:latest
    container_name: exchange-db_container
    environment:
      POSTGRES_DB: sa
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - exchange_database_data_2:/var/lib/postgresql/data_2:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: exchange-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
###> doctrine/doctrine-bundle ###
  exchange_database_data_2:

###< doctrine/doctrine-bundle ###
