controllers:
    resource:
        path: ../src/Identity/Ui
        namespace: App\Identity\Ui
    type: attribute

account_controllers:
    resource:
        path: ../src/Account/Ui
        namespace: App\Account\Ui
    type: annotation

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: {_controller: nelmio_api_doc.controller.swagger_ui}

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }